### ISSUE TITLE
How to publish the tensorflow.js project on github.io?

### ISSUE THREAD

**Issue by hongxin001** [kennysong/adversarial.js#3]
Hi,

Thanks for your excellent work. The project is very interesting and gives a webpage framework to display the adversarial attacks. I am curious about how to publish the web project built by tensorflow.js on github.io? Could you share the tutorial for that?

Best Regards

**Comment by kennysong** [comment]
The link you typed has the instructions already :)

It's just a static HTML page served by this: https://github.io

**Comment by hongxin001** [comment]
I see. I thought it should be different to serve a tensorflow.js project.

**Comment by kennysong** [comment]
It’s all running in client side JS, so can be served with a static site hosting service.
